CREATE TABLE IF NOT EXISTS users (
    username TEXT PRIMARY KEY NOT NULL,
    banned BOOLEAN NOT NULL DEFAULT false,
    scene TEXT NOT NULL DEFAULT 'map_welcome',
    x FLOAT NOT NULL DEFAULT 0,
    y FLOAT NOT NULL DEFAULT 0.9,
    z FLOAT NOT NULL DEFAULT 0,
    r FLOAT NOT NULL DEFAULT 0,
    legitTokens TEXT NOT NULL DEFAULT "",
    cheatTokens TEXT NOT NULL DEFAULT "",
    lastPlayed INT NOT NULL DEFAULT 0
);